name: ci

on:
  push:
    branches: [ master ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: source
        run: npm ci
      - name: Lint
        working-directory: source
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: source
        run: npm ci
      - name: Test
        working-directory: source
        run: "npm run test:coverage"
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: source
